# Macro file for example T1
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
/run/numberOfThreads 18
# Initialize kernel
/run/initialize
#
/geometry/test/verbosity false
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/control/verbose 0

#/control/verbose 2
#/run/verbose 2
#/event/verbose 0
#/tracking/verbose 1
/gun/particle neutron
/gun/energy 2.45 MeV
#
/run/beamOn 100000000
